name: Deploy Angular to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install dependences and build Angular
      run: |
        npm install -g @angular/cli
        npm install --force
        ng build --configuration production

    - name: Deploy via FTP to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/traceability-angular/
        server-dir: /htdocs/traceability-angular/
